#!/bin/bash
# UCE post installation script borrowed from CrunchBang Linux

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.


# First run
if [ "$1" = "--firstrun" ]; then
    if [ -d /home/ubuntu ]; then
        exit 0    
    fi
    if [ -e "/home/$USER/.config/uce/uce-welcome" ]; then
        exit 0   
    fi
fi

# Create flag
if [ ! -d "/home/$USER/.config/uce" ]; then
    mkdir /home/$USER/.config/uce
fi
if [ ! -f "/home/$USER/.config/uce/uce-welcome" ]; then
    touch /home/$USER/.config/uce/uce-welcome
    echo "X-GNOME-Autostart-enabled=false" >> ~/.config/autostart/uce-welcome.desktop
fi

# Vars
LIBDIR="/usr/share/uce-welcome-libs"
STEP="0"
STEPS=`ls -1 $LIBDIR | wc -l`
#Internet connection not counted as step, so -1
STEPS=$((STEPS-1))


# Run through steps

STEP=$((STEP+1))
. $LIBDIR/intro

. $LIBDIR/check-internet-connection


STEP=$((STEP+1))
. $LIBDIR/apt-update

STEP=$((STEP+1))
. $LIBDIR/media

STEP=$((STEP+1))
. $LIBDIR/install-skype

STEP=$((STEP+1))
. $LIBDIR/install-google-earth

STEP=$((STEP+1))
. $LIBDIR/dropbox

#STEP=$((STEP+1))
#. $LIBDIR/devel

if [ "$DEVEL" != true ]; then
    . $LIBDIR/fini
    exit 0
fi

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-version-control-tools

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-ssh-server

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-lamp-stack

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-packaging-tools

. $LIBDIR/fini
exit 0
